#-------------------------------
# General Site Settings

title: A Vivid Visual
description: Brand Identity, Web Design & Development
email: hello@avividvisual.com

# NOTE: The Logo and Background image are defined in the all.sass document.

# menu:
# - {name: About Me, url: '#about-me'}
# - {name: Work, url: '#work'}
# - {name: Clients, url: '#clients'}
# - {name: Contact, url: '#contact'}
#
#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'We build MVPs, design identities and build websites. Visualize your ideas.'
  # rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  # rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X
